const db = require("../db/connection");
const Recipe = require("../model/recipe.js");
db.on("error", console.error.bind(console, "MongoDB connection error:"));

const main = async () => {
  const recipes = [
    {
      title: "Fennel and Chicken Stew",
      coverImage: "https://i.imgur.com/3znSL1M.png",
      servesPeople: 4,
      cookTime: 1,
      cookTimeUnit: "Hour",
      ingredients: [
        {
          amountNum: 1,
          amountDen: 1,
          unit: "tsp",
          name: "olive oil",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 3,
          amountDen: 1,
          unit: "clove",
          name: "garlic",
          consistency: "minced",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 2,
          unit: "cup",
          name: "onions",
          consistency: "diced",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "cup",
          name: "celery",
          consistency: "diced",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "tsp",
          name: "fennel seeds",
          consistency: "ground",
          meta: "",
        },
        {
          amountNum: 3,
          amountDen: 1,
          unit: "",
          name: "plum tomatoes",
          consistency: "diced",
          meta: "",
        },
        {
          amountNum: 4,
          amountDen: 1,
          unit: "cup",
          name: "chicken broth",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 2,
          amountDen: 1,
          unit: "lbs",
          name: "chicken breasts",
          consistency: "diced",
          meta: "",
        },
        {
          amountNum: 2,
          amountDen: 1,
          unit: "",
          name: "potatoes",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "pinch",
          name: "garlic powder",
          consistency: "",
          meta: "",
        },
        {
          amountNum: null,
          amountDen: 0,
          unit: "",
          name: "black pepper",
          consistency: "",
          meta: "to taste",
        },
      ],
      preparation: [
        {
          step: 1,
          description:
            "Sauté the olive oil, garlic, and onion over medium heat in a large nonstick stockpot.",
          stepImage: "https://i.imgur.com/mVgiec0.png",
        },
        {
          step: 2,
          description:
            "Add the celery and fennel and sauté briefly, then add the tomatoes.",
          stepImage: "https://i.imgur.com/J6UU6Yw.png",
        },
        {
          step: 3,
          description:
            "Add the broth, chicken, potatoes, and seasonings. Cook at a simmer over medium heat until the chicken is done and the potatoes are tender, about 20-25 minutes.",
          stepImage: "https://i.imgur.com/7QIhXPs.png",
        },
      ],
      filters: {
        healthy: false,
        seasonal: false,
        min30: false,
        glutenFree: false,
        vegetarian: false,
        breakfast: false,
        lunch: false,
        dinner: true,
        dessert: false,
        snack: false,
        indian: false,
        thai: false,
        japanese: false,
        french: false,
        italian: false,
        mexican: false,
        american: true,
        canadian: false,
        korean: false,
        polish: false,
      },
      comments: [
        {
          commentAuthor: "Dan Dalgatov",
          commentDetails: "This dish is perfect for a hungry developer",
          commentTime: "1592459790537",
        },
      ],
    },
    {
      title: "Chicken Parm",
      coverImage: "https://imgur.com/3znSL1M",
      servesPeople: 4,
      cookTime: 1,
      cookTimeUnit: "Hour",
      ingredients: [
        {
          amountNum: 1,
          amountDen: 1,
          unit: "tsp",
          name: "olive oil",
          consistency: "",
          meta: "for frying",
        },
        {
          amountNum: 3,
          amountDen: 1,
          unit: "clove",
          name: "garlic",
          consistency: "minced",
          meta: "",
        },
        {
          amountNum: 0.5,
          amountDen: 1,
          unit: "cup",
          name: "onions",
          consistency: "diced",
          meta: "",
        },
        {
          amountNum: 2,
          amountDen: 1,
          unit: "tbs",
          name: "flour",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 4,
          unit: "cup",
          name: "mozzarella cheese",
          consistency: "small cubes",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 4,
          unit: "cup",
          name: "Fresh Basil",
          consistency: "chopped",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 2,
          unit: "cup",
          name: "provolone cheese",
          consistency: "grated",
          meta: "",
        },

        {
          amountNum: 1,
          amountDen: 2,
          unit: "cup",
          name: "tomato sauce",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 4,
          amountDen: 1,
          unit: "",
          name: "chicken breasts",
          consistency: "diced",
          meta: "",
        },
        {
          amountNum: 2,
          amountDen: 1,
          unit: "",
          name: "eggs",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "cup",
          name: "panko",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "pinch",
          name: "salt",
          consistency: "",
          meta: "",
        },
        {
          amountNum: null,
          amountDen: 0,
          unit: "",
          name: "black pepper",
          consistency: "",
          meta: "to taste",
        },
      ],
      preparation: [
        {
          step: 1,
          description:
            "Preheat an oven to 450 degrees F (230 degrees C). Place chicken breasts between two sheets of heavy plastic (resealable freezer bags work well) on a solid, level surface. Firmly pound chicken with the smooth side of a meat mallet to a thickness of 1/2-inch. Season chicken thoroughly with salt and pepper. Beat eggs in a shallow bowl and set aside.",
          stepImage: "https://imgur.com/mVgiec0",
        },
        {
          step: 2,
          description:
            "Mix bread crumbs and 1/2 cup Parmesan cheese in a separate bowl, set aside. Place flour in a sifter or strainer; sprinkle over chicken breasts, evenly coating both sides. Dip flour coated chicken breast in beaten eggs. Transfer breast to breadcrumb mixture, pressing the crumbs into both sides. Repeat for each breast. Set aside breaded chicken breasts for about 15 minutes.",
          stepImage: "https://imgur.com/J6UU6Yw",
        },
        {
          step: 3,
          description:
            "Heat 1 cup olive oil in a large skillet on medium-high heat until it begins to shimmer. Cook chicken until golden, about 2 minutes on each side. The chicken will finish cooking in the oven. Place chicken in a baking dish and top each breast with about 1/3 cup of tomato sauce. Layer each chicken breast with equal amount of mozzarella cheese, fresh basil, and provolone cheese. Sprinkle 1 to 2 tablespoons of Parmesan cheese on top and drizzle with 1 tablespoon olive oil. Bake in the preheated oven until cheese is browned and bubbly, and chicken breasts are no longer pink in the center, 15 to 20 minutes. An instant-read thermometer inserted into the center should read at least 165 degrees F (74 degrees C).",
          stepImage: "https://imgur.com/7QIhXPs",
        },
      ],
      filters: {
        healthy: false,
        seasonal: false,
        min30: false,
        glutenFree: false,
        vegetarian: false,
        breakfast: false,
        lunch: false,
        dinner: false,
        dessert: false,
        snack: false,
        indian: false,
        thai: false,
        japanese: false,
        french: false,
        italian: true,
        mexican: false,
        american: false,
        canadian: false,
        korean: false,
        polish: false,
      },
      comments: [
        {
          commentAuthor: "Dan Dalgatov",
          commentDetails: "This dish is perfect for a hungry developer",
          commentTime: "1592459790537",
        },
      ],
    },
    {
      title: "Spanish Rice",
      coverImage:
        "https://i.ibb.co/QjJsZrb/Screen-Shot-2020-06-21-at-4-10-05-PM.png",
      servesPeople: 2,
      cookTime: 40,
      cookTimeUnit: "Minutes",
      ingredients: [
        {
          amountNum: 2,
          amountDen: 1,
          unit: "Tbsp",
          name: "olive oil",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "clove",
          name: "garlic",
          consistency: "minced",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 2,
          unit: "",
          name: "green bell pepper or 1 jalapeno",
          consistency: "seeded and finely diced",
          meta: "",
        },
        {
          amountNum: 2,
          amountDen: 1,
          unit: "",
          name: "green onions or a handful of cilantro",
          consistency: "roughly chopped",
          meta: "",
        },
        {
          amountNum: 1.5,
          amountDen: 1,
          unit: "cups",
          name: "Tomato sauce",
          consistency: "",
          meta:
            "(or canned diced tomatoes if you want chunky tomato pieces in the rice)",
        },
        {
          amountNum: 3,
          amountDen: 1,
          unit: "cups",
          name: "chicken broth/stock",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "tsp",
          name: "salt",
          consistency: "",
          meta: "(or according to taste if the chicken broth is salty)",
        },
        {
          amountNum: 1,
          amountDen: 3,
          unit: "tsp",
          name: "black pepper",
          consistency: "ground",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "tsp",
          name: "oregano",
          consistency: "dried",
          meta: "",
        },
      ],
      preparation: [
        {
          step: 1,
          description:
            "Heat 2 tbsp of olive oil in a deep pan, on medium-high heat. Add the minced garlic and sautee for a minute or two, until it’s soft. Toss in the diced green pepper/ jalapeno and sautee it together with the garlic. Before your garlic starts burning, add the rice and stir it well so that more or less each grain is coated in oil. Sautee the rice for a couple minutes stirring to make sure the rice doesn’t stick to the bottom of the pan.",
          stepImage:
            "https://i.ibb.co/YZkgWtG/Screen-Shot-2020-06-21-at-4-10-21-PM.png",
        },
        {
          step: 2,
          description:
            "Then add 1/2 cup of tomato sauce or diced tomatoes (according to your preference) and stir it all to coat the rice. Pour in the chicken stock/broth and stir picking up all the flavor from the bottom of the pan. Season the rice with salt, pepper and oregano. Stir gently and let the broth come to a boil on high heat.",
          stepImage:
            "https://i.ibb.co/g94B88d/Screen-Shot-2020-06-21-at-4-11-43-PM.png",
        },
        {
          step: 3,
          description:
            "As soon as the liquid starts bubbling, put a lid on and turn the heat down to a low simmer and let the rice cook for about 20 mins, until most of the liquid is absorbed and the rice is tender. Add the chopped green onion or cilantro and very gently stir it in, or simple fluff the rice up with some forks. Garnish with a little green onion on top.",
          stepImage:
            "https://i.ibb.co/fF2SbBL/Screen-Shot-2020-06-21-at-4-12-43-PM.png",
        },
      ],
      filters: {
        healthy: true,
        seasonal: false,
        min30: false,
        glutenFree: false,
        vegetarian: true,
        breakfast: false,
        lunch: true,
        dinner: false,
        dessert: false,
        snack: false,
        indian: false,
        thai: false,
        japanese: false,
        french: false,
        italian: false,
        mexican: true,
        american: false,
        canadian: false,
        korean: false,
        polish: false,
      },
      comments: [
        {
          commentAuthor: "Dan Dalgatov",
          commentDetails: "This dish is perfect for a hungry developer",
          commentTime: "1592459790537",
        },
      ],
    },

    {
      title: "Zeppoli",
      coverImage:
        "https://www.olgasflavorfactory.com/wp-content/uploads/2013/07/Zeppole-1-copy.jpg",
      servesPeople: 4,
      cookTime: 1,
      cookTimeUnit: "Hour",
      ingredients: [
        {
          amountNum: 1,
          amountDen: 1,
          unit: "cup",
          name: "water",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 8,
          amountDen: 1,
          unit: "tbs",
          name: "butter",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 3,
          amountDen: 1,
          unit: "tbs",
          name: "sugar",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 4,
          unit: "tsp",
          name: "salt",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "cup",
          name: "flour",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 4,
          amountDen: 1,
          unit: "",
          name: "eggs",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 4,
          amountDen: 1,
          unit: "inches",
          name: "Frying oil",
          consistency: "",
          meta: "",
        },
      ],
      preparation: [
        {
          step: 1,
          description:
            "In a medium saucepan, combine the water, butter, sugar and salt. Cook until the butter completely melts. Add the flour all at once and mix vigorously with a wooden spoon, until the dough comes together in a ball. Continue cooking for a minute or two. Place the dough in the bowl of a standing mixer. Mix with a paddle attachment, until you don’t see any more steam rising up from the bowl.",
          stepImage:
            "https://www.olgasflavorfactory.com/wp-content/uploads/2019/10/Pate-Choux-Dough-Step-By-Step.jpg",
        },
        {
          step: 2,
          description:
            "Add the eggs, one at a time, until they are fully incorporated. You can also use a hand held mixer, or even mix up the dough by hand. Meanwhile, pour in enough oil into a large, heavy pot (I use my Dutch oven). You should have at least 2 inches of oil, I usually use one full container of oil. Heat up the oil to 375 degrees Fahrenheit. Transfer the dough to a large ziptop bag. Cut a hole in one corner. Slowly pipe out the dough and cut off snippets of the dough right into the oil. Be careful not to splash yourself. You can also use 2 small spoons to drop bits of dough into the oil, or use a small portion scoop.",
          stepImage:
            "https://www.olgasflavorfactory.com/wp-content/uploads/2019/10/Frying-Zeppole.jpg",
        },
        {
          step: 3,
          description:
            "Keep the temperature above 350 at all times, preferably 360-375 degrees. Fry the zeppole about 5 minutes, turning over the ones that don’t turn themselves over. Take them out of the oil using a slotted spoon and place them on a paper towel lined plate, baking sheet, etc. When you’re done frying all the zeppole, dust them with powdered sugar.",
          stepImage:
            "https://www.olgasflavorfactory.com/wp-content/uploads/2013/07/Zeppoles-1-2-copy.jpg",
        },
      ],
      filters: {
        healthy: false,
        seasonal: false,
        min30: false,
        glutenFree: false,
        vegetarian: false,
        breakfast: false,
        lunch: false,
        dinner: false,
        dessert: true,
        snack: false,
        indian: false,
        thai: false,
        japanese: false,
        french: false,
        italian: true,
        mexican: false,
        american: false,
        canadian: false,
        korean: false,
        polish: false,
      },
      comments: [
        {
          commentAuthor: "Dan Dalgatov",
          commentDetails: "This dish is perfect for a hungry developer",
          commentTime: "1592459790537",
        },
      ],
    },

    {
      title: "Veal Milanese",
      coverImage:
        "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2003/11/3/0/ei1a03_veal_milanese.jpg.rend.hgtvcom.826.620.suffix/1386773166905.jpeg",
      servesPeople: 6,
      cookTime: 31,
      cookTimeUnit: "Minutes",
      ingredients: [
        {
          amountNum: 4,
          amountDen: 1,
          unit: "",
          name: "eggs",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1.5,
          amountDen: 1,
          unit: "cups",
          name: "flour",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 2,
          amountDen: 1,
          unit: "cups",
          name: "Bread crumbs",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 2,
          amountDen: 1,
          unit: "tsp",
          name: "dried basil",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "tsp",
          name: "dried thyme",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 2,
          amountDen: 1,
          unit: "lbs",
          name: "veal scallopine",
          consistency: "",
          meta: "Thinly sliced",
        },
        {
          amountNum: 0,
          amountDen: 0,
          unit: "",
          name: "salt and pepper",
          consistency: "",
          meta: "to taste",
        },
      ],
      preparation: [
        {
          step: 1,
          description:
            "Preheat oven to 175 degrees F. In a shallow dish, beat eggs and season with salt and pepper. Pour flour into another shallow dish. Mix together the bread crumbs, basil and thyme in a third shallow dish. Have ready one large plate.",
          stepImage:
            "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2003/11/3/0/ei1a03_veal_milanese.jpg.rend.hgtvcom.826.620.suffix/1386773166905.jpeg",
        },
        {
          step: 2,
          description:
            "Season the veal with salt and pepper. Working with 1 piece of veal at a time, dip it first in the flour, shaking off excess. Next, place the floured veal into the beaten eggs, coating completely. Place the veal into the bread crumb mixture and gently press crumbs into the veal. Set aside on large plate and continue with remaining veal slices.",
          stepImage:
            "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2003/11/3/0/ei1a03_veal_milanese.jpg.rend.hgtvcom.826.620.suffix/1386773166905.jpeg",
        },
        {
          step: 3,
          description:
            "In a large skillet with high sides, heat the oil to 375 degrees F. Have ready a baking sheet fitted with a rack. Carefully place 2 pieces of breaded veal in the hot oil and fry until golden brown on both sides, about 6 to 8 minutes total. Place cooked veal on rack, season with salt and place in oven to keep warm. Continue with remaining veal.",
          stepImage:
            "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2003/11/3/0/ei1a03_veal_milanese.jpg.rend.hgtvcom.826.620.suffix/1386773166905.jpeg",
        },
      ],
      filters: {
        healthy: false,
        seasonal: false,
        min30: true,
        glutenFree: false,
        vegetarian: false,
        breakfast: false,
        lunch: false,
        dinner: true,
        dessert: false,
        snack: false,
        indian: false,
        thai: false,
        japanese: false,
        french: false,
        italian: true,
        mexican: false,
        american: false,
        canadian: false,
        korean: false,
        polish: false,
      },
      comments: [
        {
          commentAuthor: "Dan Dalgatov",
          commentDetails: "This dish is perfect for a hungry developer",
          commentTime: "1592459790537",
        },
      ],
    },

    {
      title: "Focaccia bread",
      coverImage:
        "https://www.gimmesomeoven.com/wp-content/uploads/2017/03/Rosemary-Focaccia-Bread-Recipe-1-2-1100x1650.jpg",
      servesPeople: 6,
      cookTime: 25,
      cookTimeUnit: "Minutes",
      ingredients: [
        {
          amountNum: 2.75,
          amountDen: 1,
          unit: "",
          name: "flour",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "tsp",
          name: "salt",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "tbs",
          name: "sugar",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 2,
          unit: "tsp",
          name: "dried basil",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "tsp",
          name: "dried thyme",
          consistency: "",
          meta: "",
        },

        {
          amountNum: 1,
          amountDen: 1,
          unit: "tbs",
          name: "active dry yeast",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "tsp",
          name: "garlic powder",
          consistency: "",
          meta: "to taste",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "tsp",
          name: "pepper",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "tbs",
          name: "salt and pepper",
          consistency: "",
          meta: "to taste",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "tsp",
          name: "dried oregano",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 0,
          amountDen: 0,
          unit: "",
          name: "salt and pepper",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "tbs",
          name: "vegitable oil",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "cup",
          name: "water",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 2,
          amountDen: 1,
          unit: "tbs",
          name: "olive oil",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "cup",
          name: "mozzarella",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "tbs",
          name: "parmersan",
          consistency: "",
          meta: "",
        },
      ],
      preparation: [
        {
          step: 1,
          description:
            "In a large bowl, stir together the flour, salt, sugar, yeast, garlic powder, oregano, thyme, basil and black pepper. Mix in the vegetable oil and water.",
          stepImage:
            "https://www.gimmesomeoven.com/wp-content/uploads/2017/03/Rosemary-Focaccia-Bread-Recipe-2-1100x1650.jpg",
        },
        {
          step: 2,
          description:
            "When the dough has pulled together, turn it out onto a lightly floured surface, and knead until smooth and elastic. Lightly oil a large bowl, place the dough in the bowl, and turn to coat with oil. Cover with a damp cloth, and let rise in a warm place for 20 minutes.",
          stepImage:
            "https://www.gimmesomeoven.com/wp-content/uploads/2017/03/Rosemary-Focaccia-Bread-Recipe-6-1100x1650.jpg",
        },
        {
          step: 3,
          description:
            "Preheat oven to 450 degrees F (230 degrees C). Punch dough down; place on greased baking sheet. Pat into a 1/2 inch thick rectangle. Brush top with olive oil. Sprinkle with Parmesan cheese and mozzarella cheese. Bake in preheated oven for 15 minutes, or until golden brown. Serve warm.",
          stepImage:
            "https://www.gimmesomeoven.com/wp-content/uploads/2017/03/Rosemary-Focaccia-Bread-Recipe-4-1100x1650.jpg",
        },
      ],
      filters: {
        healthy: false,
        seasonal: false,
        min30: true,
        glutenFree: false,
        vegetarian: true,
        breakfast: true,
        lunch: true,
        dinner: true,
        dessert: false,
        snack: false,
        indian: false,
        thai: false,
        japanese: false,
        french: false,
        italian: true,
        mexican: false,
        american: false,
        canadian: false,
        korean: false,
        polish: false,
      },
      comments: [
        {
          commentAuthor: "Dan Dalgatov",
          commentDetails: "This dish is perfect for a hungry developer",
          commentTime: "1592459790537",
        },
      ],
    },
    {
      title: "Oven Baked Korean BBQ Beef Ribs",
      coverImage: "https://i.imgur.com/3znSL1M.png",
      servesPeople: 2,
      cookTime: 1,
      cookTimeUnit: "Hour",
      ingredients: [
        {
          amount: 4,
          unit: "lbs",
          name: "beef spare ribs",
          consistency: "",
          meta: "",
        },
        {
          amount: 1,
          unit: "cup",
          name: "brown sugar",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 4,
          unit: "cup",
          name: "rice wine",
          consistency: "(mirin)",
          meta: "",
        },
        {
          amount: 1,
          unit: "",
          name: "onion",
          consistency: "",
          meta: "",
        },
        {
          amount: 2,
          unit: "tbsp",
          name: "minced garlic",
          consistency: "",
          meta: "",
        },
        {
          amount: 2,
          unit: "tbsp",
          name: "ginger",
          consistency: "minced",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 4,
          unit: "tsp",
          name: "black pepper",
          consistency: "",
          meta: "",
        },
      ],
      preparation: [
        {
          step: 1,
          description:
            "Pour the marinade over the meat and make sure it's reaching all parts of the meat. Cover the meat and transfer it to the fridge. Marinate the meat for at least 4 hrs (but ideally for 24 hrs for optimal results).",
          stepImage:
            "https://mykoreankitchen.com/wp-content/uploads/2016/10/6.-Marinating-Spare-Ribs-for-Oven-Baked-Korean-BBQ-Beef-Ribs.jpg",
        },
        {
          step: 2,
          description:
            "Preheat the oven on 100 C/ 212 F (on fan forced setting) for 20 mins. Lay down some waxed baking paper (or aluminium foil) on a baking sheet (or roasting pan). Then place the marinated rack of ribs. Splash some marinade around the ribs but discard most of sauce. Cook it for 8 hrs.",
          stepImage:
            "https://mykoreankitchen.com/wp-content/uploads/2016/10/2.-Oven-Baked-Korean-BBQ-Beef-Ribs.jpg",
        },
        {
          step: 3,
          description: "Take the meat out and carve. Serve.",
          stepImage:
            "https://mykoreankitchen.com/wp-content/uploads/2016/10/3.-Oven-Baked-Korean-BBQ-Beef-Ribs.jpg",
        },
      ],
      filters: {
        healthy: false,
        seasonal: false,
        min30: false,
        glutenFree: false,
        vegetarian: false,
        breakfast: false,
        lunch: true,
        dinner: true,
        dessert: false,
        snack: false,
        indian: false,
        thai: false,
        japanese: false,
        french: false,
        italian: false,
        mexican: false,
        american: true,
        canadian: false,
        korean: true,
        polish: false,
      },
      comments: [
        {
          commentAuthor: "Chris Knobling",
          commentDetails: "I want to bathe in a tub of this.",
          commentTime: "1592459790537",
        },
      ],
    },
    {
      title: "Beef Bulgogi Korean Tacos",
      coverImage: "https://i.imgur.com/3znSL1M.png",
      servesPeople: 8,
      cookTime: 1,
      cookTimeUnit: "Hour",
      ingredients: [
        {
          amountNum: 3,
          amountDen:1,
          unit: "",
          name: "medium green onions",
          consistency: "chopped",
          meta: "",
        },
        {
          amountNum: 3,
          amountDen:1,
          unit: "tablespoons",
          name: "sugar",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 2,
          amountDen:1,
          unit: "tablespoons",
          name: "vegetable oil",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen:1,
          unit: "lb",
          name: "beef top sirloin steak",
          consistency: "thinly sliced against the grain",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 4,
          unit: "cup",
          name: "soy sauce",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 2,
          unit: "cup",
          name: "salsa",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 2,
          unit: "teaspoon",
          name: "fresh lime juice",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 2,
          unit: "table spoon",
          name: "soy sauce",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen:1,
          unit: "cup",
          name: "fresh cilantro sprigs",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 2,
          unit: "cup",
          name: "thinly sliced red onion",
          consistency: "",
          meta: "",
        },
        {
          amount: 2,
          unit: "cups",
          name: "romaine lettuce",
          consistency: "thinnly cut",
          meta: "",
        },
      ],
      preparation: [
        {
          step: 1,
          description:
            "In 1-gallon resealable food storage plastic bag, mix beef and marinade ingredients. Seal bag. Refrigerate 30 mins.",
          stepImage: "https://i.imgur.com/mVgiec0.png",
        },
        {
          step: 2,
          description:
            "Meanwhile, in blender, place spicy salsa ingredients. Cover; blend on medium speed until smooth. Pour into small bowl. Set aside, in large bowl, mix all slaw ingredients except lettuce until well mixed. Set aside.",
          stepImage: "https://i.imgur.com/J6UU6Yw.png",
        },
        {
          step: 3,
          description:
            "Drain beef; discard marinade. Heat 12-inch nonstick skillet over medium-high heat. Cook beef in skillet 2 to 3 minutes, stirring frequently, until brown. Toss lettuce in slaw mixture. Spoon beef on warm tortillas. Drizzle with spicy salsa, and top with slaw. Sprinkle tops with sesame seed.",
          stepImage: "https://i.imgur.com/7QIhXPs.png",
        },
      ],
      filters: {
        healthy: false,
        seasonal: false,
        min30: false,
        glutenFree: false,
        vegetarian: false,
        breakfast: false,
        lunch: true,
        dinner: true,
        dessert: false,
        snack: false,
        indian: false,
        thai: false,
        japanese: false,
        french: false,
        italian: false,
        mexican: false,
        american: true,
        canadian: false,
        korean: true,
        polish: false,
      },
      comments: [
        {
          commentAuthor: "French Montana",
          commentDetails: "I'll write a song about these babies.",
          commentTime: "1592459790537",
        },
      ],
    },

    
    {
      title: "Kimchi pancake",
      coverImage: "https://www.maangchi.com/wp-content/uploads/2020/02/kimchipancake-620x349.jpg",
      servesPeople: 4,
      cookTime: 20,
      cookTimeUnit: "Minutes",
      ingredients: [
        {
          amountNum: 1,
          amountDen:2,
          unit: "pound",
          name: "Napa Cabbage Kimchi",
          consistency: "chopped",
          meta: "",
        },
        {
          amountNum: 3,
          amountDen:1,
          unit: "",
          name: "scallions",
          consistency: "chopped",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 2,
          unit: "tsp",
          name: "sugar",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen:2,
          unit: "cup",
          name: "flour",
          consistency: "",
          meta: "all purpose flour",
        },
        {
          amountNum: 1,
          amountDen: 2,
          unit: "cup",
          name: "water",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 4,
          amountDen: 1,
          unit: "tbs",
          name: "vegtable oil",
          consistency: "",
          meta: "for frying",
        },
        
      ],
      preparation: [
        {
          step: 1,
          description:
            "Combine the kimchi, kimchi brine, scallions, sugar, flour, and water in a medium bowl and mix well with a spoon. Heat a 12-inch nonstick skillet over medium heat. (If you don’t have a 12-inch skillet, use a smaller skillet to make 2 pancakes.) Add 2 tablespoons of the vegetable oil and swirl to coat the bottom of the pan.",
          stepImage: "https://www.maangchi.com/wp-content/uploads/2020/02/kimchijeon-pan-620x349.jpg",
        },
        {
          step: 2,
          description:
            "Pour the batter into the pan and spread it with the back of a spoon or a spatula to make a large circle. Cook until the bottom is golden brown and crisp, 3 to 5 minutes. Carefully turn the pancake over. Drizzle the remaining 2 tablespoons oil around the edges of the skillet, then lift the pancake with a thin spatula to allow the oil to run underneath and tilt the pan to spread it evenly.",
          stepImage: "https://www.maangchi.com/wp-content/uploads/2020/02/kimchijeon-crunchybottom-620x349.jpg",
        },
        {
          step: 3,
          description:
            "Cook until the bottom of the pancake is light golden brown and crisp, 3 to 5 minutes. Flip it one more time and cook for another minute. Slide onto a large serving platter and serve immediately.",
          stepImage: "https://www.maangchi.com/wp-content/uploads/2020/02/kimchipancake-620x349.jpg",
        },
      ],
      filters: {
        healthy: false,
        seasonal: false,
        min30: true,
        glutenFree: false,
        vegetarian: true,
        breakfast: false,
        lunch: true,
        dinner: true,
        dessert: false,
        snack: true,
        indian: false,
        thai: false,
        japanese: false,
        french: false,
        italian: false,
        mexican: false,
        american: false,
        canadian: false,
        korean: true,
        polish: false,
      },
      comments: [
        {
          commentAuthor: "French Montana",
          commentDetails: "I'll write a song about these babies.",
          commentTime: "1592459790537",
        },
      ],
    },
    {
      title: "Sweet and crunchy tofu",
      coverImage: "https://www.maangchi.com/wp-content/uploads/2020/02/kimchipancake-620x349.jpg",
      servesPeople: 4,
      cookTime: 20,
      cookTimeUnit: "Minutes",
      ingredients: [
        {
          amountNum: 2,
          amountDen:1,
          unit: "cups",
          name: "vegtable oil",
          consistency: "",
          meta: "for frying",
        },
        {
          amountNum: 14,
          amountDen:1,
          unit: "oz",
          name: "firm tofu",
          consistency: "chopped",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 4,
          unit: "cup",
          name: "potato starch",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen:3,
          unit: "cup",
          name: "ketchup",
          consistency: "",
          meta: "for sauce",
        },
        {
          amountNum: 1,
          amountDen: 4,
          unit: "cup",
          name: "rice syrup",
          consistency: "",
          meta: "for sauce",
        },
        {
          amountNum: 3,
          amountDen: 1,
          unit: "tbs",
          name: "gochujang",
          consistency: "",
          meta: " (Korean hot pepper paste) for sauce",
        },
        
      ],
      preparation: [
        {
          step: 1,
          description:
            "Combine all the seasoning sauce ingredients in a skillet. Heat over medium high heat, stirring for about 1 to 2 minutes until bubbling. Remove from the heat and set the skillet aside. We’ll reheat this just before serving. Cut the tofu into 1 x 1½ inch bite sized pieces. Pat dry with kitchen towel or paper towel.Gently put the tofu into a plastic bag and add the potato starch. Seal the bag and gently turn it over until the tofu is well and evenly coated with the starch. Remove each piece from the bag individually and transfer to a large plate or a cutting board lined with plastic wrap, leaving some space between the pieces.",
          stepImage: "https://www.maangchi.com/wp-content/uploads/2020/02/kimchijeon-pan-620x349.jpg",
        },
        {
          step: 2,
          description:
            "Heat the oil in a skillet for 5 minutes, until it reaches 330-340°F. Carefully add the tofu pieces one at a time to the hot oil. Turn the heat down to medium and let the tofu cook for about about 2 to 3 minutes, until the bottom turns light brown and the surface is a little crispy. Turn the tofu pieces with tongs or a slotted spoon—they should be firm enough to turn without breaking—and fry for another 2 to 3 minutes, occasionally turning so that all sides turn light brown and crispy. Remove from the skillet and set in a wire mesh strainer set over a bowl.Reheat the oil for 1 minute over medium-high heat and fry all the tofu again for 3 to 4  minutes, rotating and turning them over with tongs or long wooden chopsticks, until all sides are golden brown and crunchy. (for the double fry) Transfer the tofu to the strainer set over a bowl to drain the excess oil.",
          stepImage: "https://www.maangchi.com/wp-content/uploads/2020/04/coatedtofu-650x432.jpg",
        },
        {
          step: 3,
          description:
            "If you use pumpkin seeds, put them into a slotted spoon and dip them into the hot oil to fry them for just 10 seconds or so. Transfer the seeds to a small bowl and turn off the heat. Coat and serve Reheat the sauce in the skillet until bubbling. Add the fried tofu and gently mix all together until they are well coated. Transfer to a plate and sprinkle the pumpkin seeds over top. Serve as a side dish for rice.",
          stepImage: "https://www.maangchi.com/wp-content/uploads/2020/04/dubugangjeong-insta-650x650.jpg",
        },
      ],
      filters: {
        healthy: false,
        seasonal: false,
        min30: true,
        glutenFree: false,
        vegetarian: true,
        breakfast: false,
        lunch: true,
        dinner: true,
        dessert: false,
        snack: true,
        indian: false,
        thai: false,
        japanese: false,
        french: false,
        italian: false,
        mexican: false,
        american: false,
        canadian: false,
        korean: true,
        polish: false,
      },
      comments: [
        {
          commentAuthor: "French Montana",
          commentDetails: "I'll write a song about these babies.",
          commentTime: "1592459790537",
        },
      ],
    },
    
    {
      title: "Spinach artichoke dip",
      coverImage: "http://picturetherecipe.com/wp-content/uploads/2012/10/Ranch-Chicken-Stuffed-Potato-Skins-PTR4.jpg",
      servesPeople: 4,
      cookTime: 20,
      cookTimeUnit: "Minutes",
      ingredients: [
        {
          amountNum: 2,
          amountDen:1,
          unit: "cups",
          name: "shredded part-skim mozzarella cheese",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen:2,
          unit: "cup",
          name: "fat-free sour cream",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 4,
          unit: "cup",
          name: "Parmesan cheese",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen:4,
          unit: "tsp",
          name: "black pepper",
          consistency: "",
          meta: "for sauce",
        },
        {
          amountNum: 3,
          amountDen: 1,
          unit: "",
          name: "garlic cloves",
          consistency: "",
          meta: "for sauce",
        },
        {
          amountNum: 14,
          amountDen: 1,
          unit: "oz",
          name: "can of artichoke hearts",
          consistency: "drained and chopped",
          meta: " ",
        },
        {
          amountNum: 8,
          amountDen: 1,
          unit: "oz",
          name: "1/3 less fat cream cheese block",
          consistency: "cubed",
          meta: "",
        },
        {
          amountNum: 8,
          amountDen: 1,
          unit: "oz",
          name: "fat free block of cream cheese",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 10,
          amountDen: 1,
          unit: "oz",
          name: "spinach",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 13,
          amountDen: 1,
          unit: "oz",
          name: "chips of choice",
          consistency: "",
          meta: "",
        }
      ],
      preparation: [
        {
          step: 1,
          description:
            "Preheat oven to 350°. Combine 1 1/2 cups mozzarella, sour cream, 2 tablespoons Parmesan, and next 6 ingredients (through spinach) in a large bowl; stir until well blended.",
          stepImage: "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimg1.cookinglight.timeinc.net%2Fsites%2Fdefault%2Ffiles%2Fstyles%2F4_3_horizontal_-_1200x900%2Fpublic%2Fupdated_main_images%2Foh3959p118-artichoke-spinach-dip-x.jpg%3Fitok%3DLnrVz9g2",
        },
        {
          step: 2,
          description:
            "Spoon mixture into a 1 1/2-quart baking dish. Sprinkle with remaining 1/2 cup mozzarella and remaining 2 tablespoons Parmesan.",
          stepImage: "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimg1.cookinglight.timeinc.net%2Fsites%2Fdefault%2Ffiles%2Fstyles%2F4_3_horizontal_-_1200x900%2Fpublic%2Fupdated_main_images%2Foh3959p118-artichoke-spinach-dip-x.jpg%3Fitok%3DLnrVz9g2",
        },
        {
          step: 3,
          description:
            "Bake at 350° for 30 minutes or until bubbly and golden brown. Serve with tortilla chips.",
          stepImage: "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimg1.cookinglight.timeinc.net%2Fsites%2Fdefault%2Ffiles%2Fstyles%2F4_3_horizontal_-_1200x900%2Fpublic%2Fupdated_main_images%2Foh3959p118-artichoke-spinach-dip-x.jpg%3Fitok%3DLnrVz9g2",
        },
      ],
      filters: {
        healthy: false,
        seasonal: false,
        min30: true,
        glutenFree: false,
        vegetarian: true,
        breakfast: false,
        lunch: true,
        dinner: true,
        dessert: false,
        snack: true,
        indian: false,
        thai: false,
        japanese: false,
        french: false,
        italian: false,
        mexican: false,
        american: true,
        canadian: false,
        korean: false,
        polish: false,
      },
      comments: [
        {
          commentAuthor: "French Montana",
          commentDetails: "I'll write a song about these babies.",
          commentTime: "1592459790537",
        },
      ],
    },
    {
      title: "Grilled stuffed Jalapeño",
      coverImage: "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimg1.cookinglight.timeinc.net%2Fsites%2Fdefault%2Ffiles%2Fstyles%2F4_3_horizontal_-_1200x900%2Fpublic%2Fimage%2F2017%2F04%2Fmain%2Fgrilled-stuffed-jalapenos-1704w_6.jpg%3Fitok%3D5b6bb9Mn",
      servesPeople: 4,
      cookTime: 40,
      cookTimeUnit: "Minutes",
      ingredients: [
        {
          amountNum: 2,
          amountDen:1,
          unit: "",
          name: "center-cut bacon",
          consistency: "slices",
          meta: "",
        },
        {
          amountNum: 4,
          amountDen:1,
          unit: "oz",
          name: "cream cheese",
          consistency: "softened",
          meta: "",
        },
        {
          amountNum: 4,
          amountDen: 1,
          unit: "oz",
          name: "fat-free cream cheese",
          consistency: "softened",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen:1,
          unit: "oz",
          name: "extra-sharp cheddar cheese",
          consistency: "shredded",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 4,
          unit: "cup",
          name: "minced green onions",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "tsp",
          name: "fresh lime juice",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 4,
          unit: "tsp",
          name: "kosher salt",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "",
          name: "garlic clove",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 14,
          amountDen: 1,
          unit: "",
          name: "jalapeño peppers",
          consistency: "slice in halve",
          meta: "",
        },
        {
          amountNum: 2,
          amountDen: 1,
          unit: "tbs",
          name: "cilantro",
          consistency: "chopped ",
          meta: "fresh",
        },
        {
          amountNum: 2,
          amountDen: 1,
          unit: "tbs",
          name: "tomato",
          consistency: "",
          meta: "chopped seeded",
        },
      ],
      preparation: [
        {
          step: 1,
          description:
            "Preheat grill to medium-high heat.",
          stepImage: "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimg1.cookinglight.timeinc.net%2Fsites%2Fdefault%2Ffiles%2Fstyles%2F4_3_horizontal_-_1200x900%2Fpublic%2Fimage%2F2017%2F04%2Fmain%2Fgrilled-stuffed-jalapenos-1704w_6.jpg%3Fitok%3D5b6bb9Mn",
        },
        {
          step: 2,
          description:
            "Cook bacon in a skillet over medium heat until crisp. Remove bacon from pan; drain on paper towels. Crumble bacon. Combine crumbled bacon, cheeses, and next 4 ingredients (through garlic) in a bowl, stirring well to combine. Divide cheese mixture evenly to fill the pepper halves. Place peppers, cheese sides up, on grill rack or grill grate coated with cooking spray.",
          stepImage: "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimg1.cookinglight.timeinc.net%2Fsites%2Fdefault%2Ffiles%2Fstyles%2F4_3_horizontal_-_1200x900%2Fpublic%2Fimage%2F2017%2F04%2Fmain%2Fgrilled-stuffed-jalapenos-1704w_6.jpg%3Fitok%3D5b6bb9Mn",
        },
        {
          step: 3,
          description:
            "Cover and grill peppers 8 minutes or until bottoms of peppers are charred and cheese mixture is lightly browned. Place peppers on a serving platter. Sprinkle with cilantro and tomato.",
          stepImage: "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimg1.cookinglight.timeinc.net%2Fsites%2Fdefault%2Ffiles%2Fstyles%2F4_3_horizontal_-_1200x900%2Fpublic%2Fimage%2F2017%2F04%2Fmain%2Fgrilled-stuffed-jalapenos-1704w_6.jpg%3Fitok%3D5b6bb9Mn",
        },
      ],
      filters: {
        healthy: false,
        seasonal: false,
        min30: false,
        glutenFree: false,
        vegetarian: true,
        breakfast: false,
        lunch: true,
        dinner: true,
        dessert: false,
        snack: true,
        indian: false,
        thai: false,
        japanese: false,
        french: false,
        italian: false,
        mexican: false,
        american: true,
        canadian: false,
        korean: false,
        polish: false,
      },
      comments: [
        {
          commentAuthor: "French Montana",
          commentDetails: "I'll write a song about these babies.",
          commentTime: "1592459790537",
        },
      ],
    },
    {
      title: "Baked Clams",
      coverImage: "https://www.prouditaliancook.com/wp-content/uploads/2019/12/clam-platter.jpg",
      servesPeople: 4,
      cookTime: 52,
      cookTimeUnit: "Minutes",
      ingredients: [
        {
          amountNum: 1,
          amountDen:2,
          unit: "cup",
          name: "white wine",
          consistency: "dry",
          meta: "",
        },
        {
          amountNum: 32,
          amountDen:1,
          unit: "",
          name: "littleneck clams",
          consistency: "in shells, scrubbed",
          meta: "",
        },
        {
          amountNum: 1.5,
          amountDen: 1,
          unit: "tbs",
          name: "unsalted butter",
          consistency: "divided",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen:1,
          unit: "oz",
          name: "French bread baguette",
          consistency: "slice",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "slice",
          name: "applewood-smoked bacon",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 2,
          amountDen: 1,
          unit: "tsp",
          name: "shallots",
          consistency: "minced",
          meta: "",
        },
        {
          amountNum: 1.5,
          amountDen: 1,
          unit: "tsp",
          name: "fresh thyme",
          consistency: "chopped",
          meta: "",
        },
        
      ],
      preparation: [
        {
          step: 1,
          description:
            "Bring wine to a boil in a large skillet over medium-high heat. Add clams; cover and cook 4 minutes or until shells open. Remove clams from pan, reserving cooking liquid. Discard any unopened shells. Strain cooking liquid through a cheesecloth-lined sieve into a medium bowl. Cool clams. Discard top shells. Place clams, still in bottom shell halves, in a single layer on a baking sheet.",
          stepImage: "https://www.prouditaliancook.com/wp-content/uploads/2019/12/clam-platter.jpg",
        },
        {
          step: 2,
          description:
            "Return reserved cooking liquid to pan; bring to a boil over medium-high heat. Cook until reduced to 3/4 cup (about 3 minutes). Remove from heat; remove 6 tablespoons cooking liquid from pan, and reserve for another use. Add 1 1/2 teaspoons butter to cooking liquid in pan; stir until butter melts. Spoon about 1/2 teaspoon cooking liquid back into each clam shell. Preheat broiler.",
          stepImage: "https://www.prouditaliancook.com/wp-content/uploads/2019/12/clam-platter.jpg",
        },
        {
          step: 3,
          description:
            "Place bread in a food processor; pulse 10 times or until fine crumbs measure about 1/2 cup. Cook bacon in a small skillet over medium heat until crisp. Remove bacon from pan; finely chop. Add shallots to drippings in pan; sauté 30 seconds. Add 1 tablespoon butter to pan, stirring until melted. Remove pan from heat; stir in breadcrumbs and bacon. Divide breadcrumb mixture evenly among clam shell halves, pressing mixture gently into shells. Broil 1 minute or until golden brown. Sprinkle with thyme.",
          stepImage: "https://www.prouditaliancook.com/wp-content/uploads/2019/12/clam-platter.jpg",
        },
      ],
      filters: {
        healthy: false,
        seasonal: false,
        min30: false,
        glutenFree: false,
        vegetarian: false,
        breakfast: false,
        lunch: true,
        dinner: true,
        dessert: false,
        snack: true,
        indian: false,
        thai: false,
        japanese: false,
        french: false,
        italian: false,
        mexican: false,
        american: true,
        canadian: false,
        korean: false,
        polish: false,
      },
      comments: [
        {
          commentAuthor: "French Montana",
          commentDetails: "I'll write a song about these babies.",
          commentTime: "1592459790537",
        },
      ],
    },
    {
      title: "Spicy pork vidaloo",
      coverImage: "http://picturetherecipe.com/wp-content/uploads/2018/05/Vindaloo-by-PictureTheRecipe.jpg",
      servesPeople: 4,
      cookTime: 52,
      cookTimeUnit: "Minutes",
      ingredients: [
        {
          amountNum: 2,
          amountDen:1,
          unit: "lbs",
          name: "pork",
          consistency: "cubed",
          meta: "",
        },
        {
          amountNum: 7,
          amountDen:1,
          unit: "",
          name: "baby potato's",
          consistency: "halved",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 4,
          unit: "cup",
          name: "olive oil",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen:1,
          unit: "",
          name: "salt",
          consistency: "",
          meta: "to taste",
        },
        {
          amountNum: 13,
          amountDen: 1,
          unit: "",
          name: "Dry Kashmiri Chilies",
          consistency: "",
          meta: "for sauce",
        },
        {
          amountNum: 10,
          amountDen: 1,
          unit: "tbs",
          name: "cloves of Garlic",
          consistency: "",
          meta: "for sauce",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "",
          name: "small onion",
          consistency: "",
          meta: "for sauce",
        },
        {
          amountNum: 4.5,
          amountDen: 1,
          unit: "",
          name: "Cardamom Pods",
          consistency: "",
          meta: "for sauce",
        },
        {
          amountNum: 2,
          amountDen: 1,
          unit: "tsp",
          name: "Cumin Seeds",
          consistency: "",
          meta: "for sauce",
        },
        {
          amountNum: 1,
          amountDen: 2,
          unit: "tbs",
          name: "Turmeric powder",
          consistency: "",
          meta: "for sauce",
        },
        {
          amountNum: 3,
          amountDen: 1,
          unit: "tbs",
          name: "Sugar",
          consistency: "",
          meta: "for sauce",
        },
        {
          amountNum: 1,
          amountDen: 2,
          unit: "tsp",
          name: "Black Peppercorns",
          consistency: "",
          meta: "for sauce",
        },
        {
          amountNum: 1,
          amountDen: 2,
          unit: "cup",
          name: "White Vinegar",
          consistency: "",
          meta: "for sauce",
        },
        
      ],
      preparation: [
        {
          step: 1,
          description:
            "Soak the Kashmiri Chili peppers in hot water of 5-10 minutes. Then slit and de-seed the peppers. Reserve the soaking water for later. Add the soaked and de-seeded chilli peppers along with all the ingredients listed in the spice paste in a blender and blend to a smooth paste.",
          stepImage: "http://picturetherecipe.com/wp-content/uploads/2018/05/Fiery-Pork-Vindaloo-by-PictureTheRecipe.jpg",
        },
        {
          step: 2,
          description:
            "Heat 1/4 cup of oil in a frying pan on medium heat and once hot add the spice paste and cook, stirring occasionally, until the oil separates and mixture starts to sizzle, about 10-12 minutes. Once the spice paste is cooked until the oil starts separating from it take it out of the pan and set aside.",
          stepImage: "http://picturetherecipe.com/wp-content/uploads/2018/05/Vindaloo-by-PictureTheRecipe.jpg",
        },
        {
          step: 3,
          description:
            "You can now cook the the pork cubes in a slow cooker adding as much of the spice paste as you'd like on low for 6-8 hours, adding the potatoes in the last 1/2 hour of cooking. Or you can cook the pork stove top with as much of the spice paste as you would like and the reserved water the peppers soaked in. Cover and simmer on medium-low heat. This usually takes about 60-90 mins depending on how tender you'd like the pork cubes to be. Add the potatoes for the last 20 minutes of cooking time until they are cooked through.",
          stepImage: "http://picturetherecipe.com/wp-content/uploads/2018/05/Vindaloo-by-PictureTheRecipe.jpg",
        },
      ],
      filters: {
        healthy: false,
        seasonal: false,
        min30: false,
        glutenFree: false,
        vegetarian: false,
        breakfast: false,
        lunch: true,
        dinner: true,
        dessert: false,
        snack: true,
        indian: false,
        thai: false,
        japanese: false,
        french: false,
        italian: false,
        mexican: false,
        american: true,
        canadian: false,
        korean: false,
        polish: false,
      },
      comments: [
        {
          commentAuthor: "French Montana",
          commentDetails: "I'll write a song about these babies.",
          commentTime: "1592459790537",
        },
      ],
    },
    {
    title: "Canadian Meatballs",
    coverImage: "https://www.tasteofhome.com/wp-content/uploads/2018/01/Canadian-Meatballs_exps118776_BAFTB2307047A01_19_7bC_RMS-1-696x696.jpg",
    servesPeople: 5,
    cookTime: 1,
    cookTimeUnit: "hour",
    ingredients: [
      {
        amount: 2,
        amountDen:1,
        unit: "",
        name: "Large Eggs",
        consistency: "lighty beaten",
        meta: "",
      },
      {
        amountNum: 1,
        amountDen:2,
        unit: "cup",
        name: "evaporated milk",
        consistency: "",
        meta: "",
      },
      {
        amountNum: 1,
        amountDen: 1,
        unit: "cup",
        name: "chedder cheese",
        consistency: "shredded",
        meta: "",
      },
      {
        amountNum: 2,
        amountDen:3,
        unit: "cup",
        name: "onion",
        consistency: "finely chopped",
        meta: "",
      },
      {
        amountNum: 1,
        amountDen: 1,
        unit: "lb.",
        name: "bulk pork sausage",
        consistency: "",
        meta: "",
      },
      {
        amountNum: 2,
        amountDen: 1,
        unit: "tbs",
        name: "cornstarch",
        consistency: "",
        meta: "",
      },
      {
        amountNum: 1,
        amountDen: 1,
        unit: "cup",
        name: "chile sauce",
        consistency: "",
        meta: "",
      },
      {
        amountNum: 1,
        amountDen: 1,
        unit: "cup",
        name: "maple syrup",
        consistency: "",
        meta: "",
      },
      {
        amountNum: 2,
        amountDen: 1,
        unit: "tbs",
        name: "Worcestershire sauce",
        consistency: "",
        meta: "",
      },
      {
        amountNum: 2,
        amountDen: 1,
        unit: "tbs",
        name: "maple flavoring",
        consistency: "",
        meta: "",
      },
    ],
    preparation: [
      {
        step: 1,
        description:
          "Bring wine to a boil in a large skillet over medium-high heat. Add clams; cover and cook 4 minutes or until shells open. Remove clams from pan, reserving cooking liquid. Discard any unopened shells. Strain cooking liquid through a cheesecloth-lined sieve into a medium bowl. Cool clams. Discard top shells. Place clams, still in bottom shell halves, in a single layer on a baking sheet.",
        stepImage: "https://www.prouditaliancook.com/wp-content/uploads/2019/12/clam-platter.jpg",
      },
      {
        step: 2,
        description:
          "Place meatballs on a greased rack in a shallow baking pan. Bake, uncovered, at 400° for 15-20 minutes or until a thermometer reads 160°. Drain onto paper towels.",
        stepImage: "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimg1.cookinglight.timeinc.net%2Fsites%2Fdefault%2Ffiles%2Fstyles%2F4_3_horizontal_-_1200x900%2Fpublic%2Fimage%2F2017%2F04%2Fmain%2Fgrilled-stuffed-jalapenos-1704w_6.jpg%3Fitok%3D5b6bb9Mn",
      },
      {
        step: 3,
        description:
          "Meanwhile, in a large skillet, whisk the sauce ingredients until smooth. Bring to a boil. Cook and stir for 1-2 minutes or until thickened. Add meatballs; stir to coat.",
        stepImage: "https://imagesvc.meredithcorp.io/v3/mm/image?url=https%3A%2F%2Fimg1.cookinglight.timeinc.net%2Fsites%2Fdefault%2Ffiles%2Fstyles%2F4_3_horizontal_-_1200x900%2Fpublic%2Fimage%2F2017%2F04%2Fmain%2Fgrilled-stuffed-jalapenos-1704w_6.jpg%3Fitok%3D5b6bb9Mn",
      },
    ],
    filters: {
      healthy: false,
      seasonal: false,
      min30: false,
      glutenFree: false,
      vegetarian: false,
      breakfast: false,
      lunch: true,
      dinner: true,
      dessert: false,
      snack: true,
      indian: false,
      thai: false,
      japanese: false,
      french: false,
      italian: false,
      mexican: false,
      american: false,
      canadian: true,
      korean: false,
      polish: false,
    },
    comments: [
      {
        commentAuthor: "Sam Soda",
        commentDetails: "They make me want to move to Canada.",
        commentTime: "1592459790537",
      },
    ],
  },
  {
   title: "French Canadian Meat Pie",
    coverImage: "https://www.tasteofhome.com/wp-content/uploads/2018/01/exps16208_TH10206C29C.jpg",
    servesPeople: 5,
    cookTime: 1,
    cookTimeUnit: "hour",
    ingredients: [
      {
        amount: 1,
        amountDen:1,
        unit: "lb",
        name: "ground beef",
        consistency: "",
        meta: "",
      },
      {
        amountNum: 3,
        amountDen:4,
        unit: "lb",
        name: "ground pork",
        consistency: "",
        meta: "",
      },
      {
        amountNum: 2,
        amountDen: 1,
        unit: "",
        name: "celery ribs",
        consistency: "",
        meta: "",
      },
      {
        amountNum: 2,
        amountDen:1,
        unit: "",
        name: "garlic cloves",
        consistency: "minced",
        meta: "",
      },
      {
        amountNum: 6,
        amountDen: 1,
        unit: "cups",
        name: "hot mashed potatoes",
        consistency: "(prepared without milk or butter)",
        meta: "",
      },
      {
        amountNum: 1,
        amountDen: 4,
        unit: "cup",
        name: "olive oil",
        consistency: "",
        meta: "",
      },
      {
        amountNum: 1,
        amountDen:1,
        unit: "",
        name: "salt",
        consistency: "",
        meta: "to taste",
      },
      {
        amountNum: 13,
        amountDen: 1,
        unit: "",
        name: "Dry Kashmiri Chilies",
        consistency: "",
        meta: "for sauce",
      },
      {
        amountNum: 10,
        amountDen: 1,
        unit: "tbs",
        name: "cloves of Garlic",
        consistency: "",
        meta: "for sauce",
      },
      {
        amountNum: 1,
        amountDen: 1,
        unit: "",
        name: "small onion",
        consistency: "",
        meta: "for sauce",
      },
      {
        amountNum: 4.5,
        amountDen: 1,
        unit: "",
        name: "Cardamom Pods",
        consistency: "",
        meta: "for sauce",
      },
      {
        amountNum: 2,
        amountDen: 1,
        unit: "tsp",
        name: "Cumin Seeds",
        consistency: "",
        meta: "for sauce",
      },
      {
        amountNum: 1,
        amountDen: 2,
        unit: "tbs",
        name: "Turmeric powder",
        consistency: "",
        meta: "for sauce",
      },
      {
        amountNum: 3,
        amountDen: 1,
        unit: "tbs",
        name: "Sugar",
        consistency: "",
        meta: "for sauce",
      },
      {
        amountNum: 1,
        amountDen: 2,
        unit: "tsp",
        name: "Black Peppercorns",
        consistency: "",
        meta: "for sauce",
      },
      {
        amountNum: 1,
        amountDen: 2,
        unit: "cup",
        name: "White Vinegar",
        consistency: "",
        meta: "for sauce",
      },
    ],
    preparation: [
      {
        step: 1,
        description:
          "In a large skillet, cook the beef, pork, onion and celery over medium heat until meat is no longer pink. Add garlic; cook 1 minute longer. Drain. Remove from the heat. Stir in the potatoes, broth and seasonings.",
        stepImage: "https://www.tasteofhome.com/wp-content/uploads/2018/01/exps16208_TH10206C29C.jpg",
      },
      {
        step: 2,
        description:
          "Line two 9-in. pie plates with pastry. Divide meat mixture between crusts. Top with remaining pastry; trim, seal and flute edges.",
        stepImage: "https://www.tasteofhome.com/wp-content/uploads/2018/01/exps16208_TH10206C29C.jpg",
      },
      {
        step: 3,
        description:
          "Cut slits in top. Brush with milk if desired. Bake at 375° for 30-35 minutes or until golden brown.",
        stepImage: "https://www.tasteofhome.com/wp-content/uploads/2018/01/exps16208_TH10206C29C.jpg",
      },
    ],
    filters: {
      healthy: false,
      seasonal: false,
      min30: false,
      glutenFree: false,
      vegetarian: false,
      breakfast: false,
      lunch: false,
      dinner: true,
      dessert: false,
      snack: false,
      indian: false,
      thai: false,
      japanese: false,
      french: true,
      italian: false,
      mexican: false,
      american: false,
      canadian: true,
      korean: false,
      polish: false,
    },
    comments: [
      {
        commentAuthor: "French Montana",
        commentDetails: "I'll write a song about these babies.",
        commentTime: "1592459790537",
      },
    ],
  },
  {
    title: "Palak Paneer",
     coverImage: "http://picturetherecipe.com/wp-content/uploads/2020/04/Palak-Paneer-Story-by-PictureTheRecipe.jpg",
     servesPeople: 4,
     cookTime: 20,
     cookTimeUnit: "Minutes",
     ingredients: [
       {
         amount: 1,
         amountDen:1,
         unit: "cup",
         name: "Paneer",
         consistency: "cubed",
         meta: "",
       },
       {
         amountNum: 3,
         amountDen:1,
         unit: "cups",
         name: "spinach",
         consistency: "",
         meta: "",
       },
       {
         amountNum: 2,
         amountDen: 1,
         unit: "tbsp",
         name: "oil/butter",
         consistency: "",
         meta: "",
       },
       {
         amountNum: 2,
         amountDen:1,
         unit: "",
         name: "green chilies",
         consistency: "thai peppers",
         meta: "Adjust to your heat level",
       },
       {
         amountNum: 3,
         amountDen: 4,
         unit: "cups",
         name: "onion",
         consistency: "diced",
         meta: "",
       },
       {
         amountNum: 1,
         amountDen: 1,
         unit: "tsp",
         name: "garlic-ginger paste",
         consistency: "",
         meta: "",
       },
       {
         amountNum: 1,
         amountDen:2,
         unit: "cup",
         name: "tomatos",
         consistency: "",
         meta: "",
       },
       {
         amountNum: 1,
         amountDen: 2,
         unit: "tsp",
         name: "kasuri methi",
         consistency: "",
         meta: "dried fenugreek leaves (optional)",
       },
       {
         amountNum: 8,
         amountDen: 1,
         unit: "",
         name: "cashews",
         consistency: "",
         meta: "soaked in warm water and blendid to paste",
       },
       {
         amountNum: 1,
         amountDen: 4,
         unit: "cup",
         name: "heavy cream",
         consistency: "",
         meta: "",
       },
       {
         amountNum: 2,
         amountDen: 1,
         unit: "",
         name: " Green Cardamom Pods",
         consistency: "",
         meta: "",
       },
       {
         amountNum: 1,
         amountDen: 4,
         unit: "tsp",
         name: "Cumin Seeds",
         consistency: "",
         meta: "",
       },
       {
         amountNum: 2,
         amountDen: 1,
         unit: "",
         name: "cloves",
         consistency: "",
         meta: "",
       },
       {
         amountNum: 1,
         amountDen: 1,
         unit: "tsp",
         name: "coriander powder",
         consistency: "",
         meta: "",
       },
       {
         amountNum: 1,
         amountDen: 2,
         unit: "tsp",
         name: "",
         consistency: "",
         meta: "for sauce",
       },
     ],
     preparation: [
       {
         step: 1,
         description:
           "Add a teaspoon oil in a pan and add the sliced green chilies and spinach leaves. Cook the leaves until just wilted, but avoid overcooking to retain its vibrant green color. Set aside to cool. Once cooled blend the spinach and green chilies to a smooth puree.To make the gravy- heat oil in a pan and add the whole spices. as soon as they begin to splutter add the onions and sauté on medium high heat until they turn translucent.",
         stepImage: "http://picturetherecipe.com/wp-content/uploads/2018/05/Fiery-Pork-Vindaloo-by-PictureTheRecipe.jpg",
       },
       {
         step: 2,
         description:
           "Add the ginger garlic paste and fry until the raw smell goes away. Add the tomatoes and season with salt. cook the tomatoes down until they turn mushy. The add the kasuri methi and spice powders and fry the mixture until it starts releasing oil. Pour in half a cup of water and stir until the mixture thickens. Lower the heat and add the spinach puree. mix well until it comes to a gentle simmer.",
         stepImage: "http://picturetherecipe.com/wp-content/uploads/2018/05/Vindaloo-by-PictureTheRecipe.jpg",
       },
       {
         step: 3,
         description:
           "(optional) Pan fry the paneer cubes with 1-2 tsp oil for 2-3 mins until golden on each side in a separate pan. Add the paneer cubes to the spinach mixture and turn off the heat. Add the cashew paste mixed with the cream and stir it in for added creaminess. Reserve some for garnish.",
         stepImage: "http://picturetherecipe.com/wp-content/uploads/2018/05/Vindaloo-by-PictureTheRecipe.jpg",
       },
     ],
     filters: {
       healthy: true,
       seasonal: false,
       min30: true,
       glutenFree: false,
       vegetarian: true,
       breakfast: true,
       lunch: true,
       dinner: true,
       dessert: false,
       snack: false,
       indian: true,
       thai: false,
       japanese: false,
       french: false,
       italian: false,
       mexican: false,
       american: false,
       canadian: false,
       korean: false,
       polish: false,
     },
     comments: [
       {
         commentAuthor: "French Montana",
         commentDetails: "I'll write a song about these babies.",
         commentTime: "1592459790537",
       },
     ],
   },
   {
    title: "Moroccan chickpea stew",
     coverImage: "http://picturetherecipe.com/wp-content/uploads/2015/02/Moroccan-Chickpea-Stew-with-Butternut-Squash-by-PictureTheRecipe-com.jpg",
     servesPeople: 4,
     cookTime: 40,
     cookTimeUnit: "Minutes",
     ingredients: [
       {
         amount: 1,
         amountDen:1,
         unit: "can",
         name: "Chickpeas",
         consistency: "cubed",
         meta: "",
       },
       {
         amountNum: 3,
         amountDen:1,
         unit: "",
         name: "tomatoes",
         consistency: "",
         meta: "cubed",
       },
       {
         amountNum: 1,
         amountDen: 1,
         unit: "",
         name: "onion",
         consistency: "grated",
         meta: "",
       },
       {
         amountNum: 3,
         amountDen:1,
         unit: "cloves",
         name: "garlic",
         consistency: "grated",
         meta: "",
       },
       {
         amountNum: 1,
         amountDen: 1,
         unit: "cup",
         name: "butternut squash",
         consistency: "diced",
         meta: "",
       },
       {
         amountNum: 1,
         amountDen: 1,
         unit: "",
         name: "zucchini",
         consistency: "diced",
         meta: "",
       },
       {
         amountNum: 1,
         amountDen:1,
         unit: "tbs",
         name: "chili paste",
         consistency: "",
         meta: "Please adjust to your spice level",
       },
       {
         amountNum: 1,
         amountDen: 2,
         unit: "tsp",
         name: "paprika",
         consistency: "",
         meta: "",
       },
       {
         amountNum: 1,
         amountDen: 2,
         unit: "tsp",
         name: "cumin",
         consistency: "",
         meta: "soaked in warm water and blendid to paste",
       },
       {
         amountNum: 1,
         amountDen: 1,
         unit: "tsp",
         name: "coriander powder",
         consistency: "",
         meta: "",
       },
       {
         amountNum: 1,
         amountDen: 1,
         unit: "tsp",
         name: "dried oregano",
         consistency: "",
         meta: "",
       },
       {
         amountNum: 1,
         amountDen: 2,
         unit: "tsp",
         name: "dried thyme",
         consistency: "",
         meta: "",
       },
       {
         amountNum: 1,
         amountDen: 4,
         unit: "tsp",
         name: "cinnamon",
         consistency: "",
         meta: "",
       },
       {
         amountNum: 1,
         amountDen: 1,
         unit: "tbs",
         name: "sugar (optional)",
         consistency: "",
         meta: "",
       },
       {
         amountNum: 1,
         amountDen: 1,
         unit: "",
         name: "Juice of 1/2 lemon",
         consistency: "",
         meta: "",
       },
     ],
     preparation: [
       {
         step: 1,
         description:
           "If you want to use fresh tomatoes over a canned puree, first score an 'x' on the bottom of the tomatoes. Submerge them in a pot of water, cover it and bring to a rapid boil. As soon as the tomatoes blister and the peel starts loosening off, turn the heat off, drain the water and allow them to cool before peeling and pureeing them in a blender/food processor. To prep the vegetables, grate (or pulse in a food processor) one medium onion and the garlic cloves. Peel and dice about a cup of butternut squash and one zucchini (leaving the skin on the zucchini). And finely chop a generous handful of parsley. Heat the olive oil in a deep pan, then add the grated onion and saute for 3-4 minutes until they turn soft and translucent. Then toss in the grated garlic and chili paste and saute the mix for another minute or so.",
         stepImage: "http://picturetherecipe.com/wp-content/uploads/2015/02/Moroccan-Chickpea-Stew-with-Butternut-Squash-by-PictureTheRecipe-com.jpg",
       },
       {
         step: 2,
         description:
           "Add the paprika, cumin, coriander powder, oregano, thyme and cinnamon powder. Give it a quick stir!) to fry off the spices so they don't have that raw taste. Pour in the tomato puree and mix everything well scraping any brown bits on the bottom of the pan. Season the mixture with salt and pepper according to your taste. Next add in the butternut squash, chickpeas with the water and zucchini into the pot",
         stepImage: "http://picturetherecipe.com/wp-content/uploads/2015/02/Moroccan-Chickpea-Stew-with-Butternut-Squash-by-PictureTheRecipe-com.jpg",
       },
       {
         step: 3,
         description:
           "Stir in 1 tbsp of sugar (optional), the juice of 1/4 of a lemon and pinch of the freshly cut parsley (reserving the other 1/4 lemon and parsley for a garnish). Cover and let the stew simmer on low for 15-20 minutes stirring occasionally until the butternut squash is tender and fork ready. When you're ready to serve sprinkle in some sumac (a middle eastern dried and powdered berry that's tangy, similar to juniper berry), a squeeze of lemon juice and the remaining chopped parsley. Serve hot over couscous or rice.",
         stepImage: "http://picturetherecipe.com/wp-content/uploads/2015/02/Moroccan-Chickpea-Stew-with-Butternut-Squash-by-PictureTheRecipe-com.jpg",
       },
     ],
     filters: {
       healthy: true,
       seasonal: false,
       min30: false,
       glutenFree: false,
       vegetarian: true,
       breakfast: false,
       lunch: true,
       dinner: true,
       dessert: false,
       snack: false,
       indian: true,
       thai: false,
       japanese: false,
       french: false,
       italian: false,
       mexican: false,
       american: false,
       canadian: false,
       korean: false,
       polish: false,
     },
     comments: [
       {
         commentAuthor: "French Montana",
         commentDetails: "I'll write a song about these babies.",
         commentTime: "1592459790537",
       },
     ],
   },

  ]
  await Recipe.insertMany(recipes);
  console.log("Created recipes!");
};
const run = async () => {
  await main();
  db.close();
};
run();
