const db = require("../db/connection");
const Recipe = require("../model/recipe.js");
db.on("error", console.error.bind(console, "MongoDB connection error:"));

const main = async () => {
  const recipes = [
    {
      title: "Fennel and Chicken Stew",
      coverImage: "https://i.imgur.com/3znSL1M.png",
      servesPeople: 4,
      cookTime: 1,
      cookTimeUnit: "Hour",
      ingredients: [
        {
          amountNum: 1,
          amountDen: 1,
          unit: "tsp",
          name: "olive oil",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 3,
          amountDen: 1,
          unit: "clove",
          name: "garlic",
          consistency: "minced",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 2,
          unit: "cup",
          name: "onions",
          consistency: "diced",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "cup",
          name: "celery",
          consistency: "diced",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "tsp",
          name: "fennel seeds",
          consistency: "ground",
          meta: "",
        },
        {
          amountNum: 3,
          amountDen: 1,
          unit: "",
          name: "plum tomatoes",
          consistency: "diced",
          meta: "",
        },
        {
          amountNum: 4,
          amountDen: 1,
          unit: "cup",
          name: "chicken broth",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 2,
          amountDen: 1,
          unit: "",
          name: "chicken breasts",
          consistency: "diced",
          meta: "",
        },
        {
          amountNum: 2,
          amountDen: 1,
          unit: "",
          name: "potatoes",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "pinch",
          name: "garlic powder",
          consistency: "",
          meta: "",
        },
        {
          amountNum: null,
          amountDen: 0,
          unit: "",
          name: "black pepper",
          consistency: "",
          meta: "to taste",
        },
      ],
      preparation: [
        {
          step: 1,
          description:
            "Sauté the olive oil, garlic, and onion over medium heat in a large nonstick stockpot.",
          stepImage: "https://i.imgur.com/mVgiec0.png",
        },
        {
          step: 2,
          description:
            "Add the celery and fennel and sauté briefly, then add the tomatoes.",
          stepImage: "https://i.imgur.com/J6UU6Yw.png",
        },
        {
          step: 3,
          description:
            "Add the broth, chicken, potatoes, and seasonings. Cook at a simmer over medium heat until the chicken is done and the potatoes are tender, about 20-25 minutes.",
          stepImage: "https://i.imgur.com/7QIhXPs.png",
        },
      ],
      filters: {
        healthy: false,
        seasonal: false,
        min30: false,
        glutenFree: false,
        vegetarian: false,
        breakfast: false,
        lunch: false,
        dinner: true,
        dessert: false,
        snack: false,
        indian: false,
        thai: false,
        japanese: false,
        french: false,
        italian: false,
        mexican: false,
        american: true,
        canadian: false,
        korean: false,
        polish: false,
      },
      comments: [
        {
          commentAuthor: "Dan Dalgatov",
          commentDetails: "This dish is perfect for a hungry developer",
          commentTime: "1592459790537",
        },
      ],
    },
    {
      title: "Chicken Parm",
      coverImage: "https://imgur.com/3znSL1M",
      servesPeople: 4,
      cookTime: 1,
      cookTimeUnit: "Hour",
      ingredients: [
        {
          amountNum: 1,
          amountDen: 1,
          unit: "tsp",
          name: "olive oil",
          consistency: "",
          meta: "for frying",
        },
        {
          amountNum: 3,
          amountDen: 1,
          unit: "clove",
          name: "garlic",
          consistency: "minced",
          meta: "",
        },
        {
          amountNum: 0.5,
          amountDen: 1,
          unit: "cup",
          name: "onions",
          consistency: "diced",
          meta: "",
        },
        {
          amountNum: 2,
          amountDen: 1,
          unit: "tbs",
          name: "flour",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 4,
          unit: "cup",
          name: "mozzarella cheese",
          consistency: "small cubes",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 4,
          unit: "cup",
          name: "Fresh Basil",
          consistency: "chopped",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 2,
          unit: "cup",
          name: "provolone cheese",
          consistency: "grated",
          meta: "",
        },

        {
          amountNum: 1,
          amountDen: 2,
          unit: "cup",
          name: "tomato sauce",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 4,
          amountDen: 1,
          unit: "",
          name: "chicken breasts",
          consistency: "diced",
          meta: "",
        },
        {
          amountNum: 2,
          amountDen: 1,
          unit: "",
          name: "eggs",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "cup",
          name: "panko",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "pinch",
          name: "salt",
          consistency: "",
          meta: "",
        },
        {
          amountNum: null,
          amountDen: 0,
          unit: "",
          name: "black pepper",
          consistency: "",
          meta: "to taste",
        },
      ],
      preparation: [
        {
          step: 1,
          description:
            "Preheat an oven to 450 degrees F (230 degrees C). Place chicken breasts between two sheets of heavy plastic (resealable freezer bags work well) on a solid, level surface. Firmly pound chicken with the smooth side of a meat mallet to a thickness of 1/2-inch. Season chicken thoroughly with salt and pepper. Beat eggs in a shallow bowl and set aside.",
          stepImage: "https://imgur.com/mVgiec0",
        },
        {
          step: 2,
          description:
            "Mix bread crumbs and 1/2 cup Parmesan cheese in a separate bowl, set aside. Place flour in a sifter or strainer; sprinkle over chicken breasts, evenly coating both sides. Dip flour coated chicken breast in beaten eggs. Transfer breast to breadcrumb mixture, pressing the crumbs into both sides. Repeat for each breast. Set aside breaded chicken breasts for about 15 minutes.",
          stepImage: "https://imgur.com/J6UU6Yw",
        },
        {
          step: 3,
          description:
            "Heat 1 cup olive oil in a large skillet on medium-high heat until it begins to shimmer. Cook chicken until golden, about 2 minutes on each side. The chicken will finish cooking in the oven. Place chicken in a baking dish and top each breast with about 1/3 cup of tomato sauce. Layer each chicken breast with equal amount of mozzarella cheese, fresh basil, and provolone cheese. Sprinkle 1 to 2 tablespoons of Parmesan cheese on top and drizzle with 1 tablespoon olive oil. Bake in the preheated oven until cheese is browned and bubbly, and chicken breasts are no longer pink in the center, 15 to 20 minutes. An instant-read thermometer inserted into the center should read at least 165 degrees F (74 degrees C).",
          stepImage: "https://imgur.com/7QIhXPs",
        },
      ],
      filters: {
        healthy: false,
        seasonal: false,
        min30: false,
        glutenFree: false,
        vegetarian: false,
        breakfast: false,
        lunch: false,
        dinner: false,
        dessert: false,
        snack: false,
        indian: false,
        thai: false,
        japanese: false,
        french: false,
        italian: true,
        mexican: false,
        american: false,
        canadian: false,
        korean: false,
        polish: false,
      },
      comments: [
        {
          commentAuthor: "Dan Dalgatov",
          commentDetails: "This dish is perfect for a hungry developer",
          commentTime: "1592459790537",
        },
      ],
    },
    {
      title: "Spanish Rice",
      coverImage:
        "https://i.ibb.co/QjJsZrb/Screen-Shot-2020-06-21-at-4-10-05-PM.png",
      servesPeople: 2,
      cookTime: 40,
      cookTimeUnit: "Minutes",
      ingredients: [
        {
          amountNum: 2,
          amountDen: 1,
          unit: "Tbsp",
          name: "olive oil",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "clove",
          name: "garlic",
          consistency: "minced",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 2,
          unit: "",
          name: "green bell pepper or 1 jalapeno",
          consistency: "seeded and finely diced",
          meta: "",
        },
        {
          amountNum: 2,
          amountDen: 1,
          unit: "",
          name: "green onions or a handful of cilantro",
          consistency: "roughly chopped",
          meta: "",
        },
        {
          amountNum: 1.5,
          amountDen: 1,
          unit: "cups",
          name: "Tomato sauce",
          consistency: "",
          meta:
            "(or canned diced tomatoes if you want chunky tomato pieces in the rice)",
        },
        {
          amountNum: 3,
          amountDen: 1,
          unit: "cups",
          name: "chicken broth/stock",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "tsp",
          name: "salt",
          consistency: "",
          meta: "(or according to taste if the chicken broth is salty)",
        },
        {
          amountNum: 1,
          amountDen: 3,
          unit: "tsp",
          name: "black pepper",
          consistency: "ground",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "tsp",
          name: "oregano",
          consistency: "dried",
          meta: "",
        },
      ],
      preparation: [
        {
          step: 1,
          description:
            "Heat 2 tbsp of olive oil in a deep pan, on medium-high heat. Add the minced garlic and sautee for a minute or two, until it’s soft. Toss in the diced green pepper/ jalapeno and sautee it together with the garlic. Before your garlic starts burning, add the rice and stir it well so that more or less each grain is coated in oil. Sautee the rice for a couple minutes stirring to make sure the rice doesn’t stick to the bottom of the pan.",
          stepImage:
            "https://i.ibb.co/YZkgWtG/Screen-Shot-2020-06-21-at-4-10-21-PM.png",
        },
        {
          step: 2,
          description:
            "Then add 1/2 cup of tomato sauce or diced tomatoes (according to your preference) and stir it all to coat the rice. Pour in the chicken stock/broth and stir picking up all the flavor from the bottom of the pan. Season the rice with salt, pepper and oregano. Stir gently and let the broth come to a boil on high heat.",
          stepImage:
            "https://i.ibb.co/g94B88d/Screen-Shot-2020-06-21-at-4-11-43-PM.png",
        },
        {
          step: 3,
          description:
            "As soon as the liquid starts bubbling, put a lid on and turn the heat down to a low simmer and let the rice cook for about 20 mins, until most of the liquid is absorbed and the rice is tender. Add the chopped green onion or cilantro and very gently stir it in, or simple fluff the rice up with some forks. Garnish with a little green onion on top.",
          stepImage:
            "https://i.ibb.co/fF2SbBL/Screen-Shot-2020-06-21-at-4-12-43-PM.png",
        },
      ],
      filters: {
        healthy: true,
        seasonal: false,
        min30: false,
        glutenFree: false,
        vegetarian: true,
        breakfast: false,
        lunch: true,
        dinner: false,
        dessert: false,
        snack: false,
        indian: false,
        thai: false,
        japanese: false,
        french: false,
        italian: false,
        mexican: true,
        american: false,
        canadian: false,
        korean: false,
        polish: false,
      },
      comments: [
        {
          commentAuthor: "Dan Dalgatov",
          commentDetails: "This dish is perfect for a hungry developer",
          commentTime: "1592459790537",
        },
      ],
    },

    {
      title: "Zeppoli",
      coverImage:
        "https://www.olgasflavorfactory.com/wp-content/uploads/2013/07/Zeppole-1-copy.jpg",
      servesPeople: 4,
      cookTime: 1,
      cookTimeUnit: "Hour",
      ingredients: [
        {
          amountNum: 1,
          amountDen: 1,
          unit: "cup",
          name: "water",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 8,
          amountDen: 1,
          unit: "tbs",
          name: "butter",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 3,
          amountDen: 1,
          unit: "tbs",
          name: "sugar",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 4,
          unit: "tsp",
          name: "salt",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "cup",
          name: "flour",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 4,
          amountDen: 1,
          unit: "",
          name: "eggs",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 4,
          amountDen: 1,
          unit: "inches",
          name: "Frying oil",
          consistency: "",
          meta: "",
        },
      ],
      preparation: [
        {
          step: 1,
          description:
            "In a medium saucepan, combine the water, butter, sugar and salt. Cook until the butter completely melts. Add the flour all at once and mix vigorously with a wooden spoon, until the dough comes together in a ball. Continue cooking for a minute or two. Place the dough in the bowl of a standing mixer. Mix with a paddle attachment, until you don’t see any more steam rising up from the bowl.",
          stepImage:
            "https://www.olgasflavorfactory.com/wp-content/uploads/2019/10/Pate-Choux-Dough-Step-By-Step.jpg",
        },
        {
          step: 2,
          description:
            "Add the eggs, one at a time, until they are fully incorporated. You can also use a hand held mixer, or even mix up the dough by hand. Meanwhile, pour in enough oil into a large, heavy pot (I use my Dutch oven). You should have at least 2 inches of oil, I usually use one full container of oil. Heat up the oil to 375 degrees Fahrenheit. Transfer the dough to a large ziptop bag. Cut a hole in one corner. Slowly pipe out the dough and cut off snippets of the dough right into the oil. Be careful not to splash yourself. You can also use 2 small spoons to drop bits of dough into the oil, or use a small portion scoop.",
          stepImage:
            "https://www.olgasflavorfactory.com/wp-content/uploads/2019/10/Frying-Zeppole.jpg",
        },
        {
          step: 3,
          description:
            "Keep the temperature above 350 at all times, preferably 360-375 degrees. Fry the zeppole about 5 minutes, turning over the ones that don’t turn themselves over. Take them out of the oil using a slotted spoon and place them on a paper towel lined plate, baking sheet, etc. When you’re done frying all the zeppole, dust them with powdered sugar.",
          stepImage:
            "https://www.olgasflavorfactory.com/wp-content/uploads/2013/07/Zeppoles-1-2-copy.jpg",
        },
      ],
      filters: {
        healthy: false,
        seasonal: false,
        min30: false,
        glutenFree: false,
        vegetarian: false,
        breakfast: false,
        lunch: false,
        dinner: false,
        dessert: true,
        snack: false,
        indian: false,
        thai: false,
        japanese: false,
        french: false,
        italian: true,
        mexican: false,
        american: false,
        canadian: false,
        korean: false,
        polish: false,
      },
      comments: [
        {
          commentAuthor: "Dan Dalgatov",
          commentDetails: "This dish is perfect for a hungry developer",
          commentTime: "1592459790537",
        },
      ],
    },

    {
      title: "Veal Milanese",
      coverImage:
        "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2003/11/3/0/ei1a03_veal_milanese.jpg.rend.hgtvcom.826.620.suffix/1386773166905.jpeg",
      servesPeople: 6,
      cookTime: 31,
      cookTimeUnit: "Minutes",
      ingredients: [
        {
          amountNum: 4,
          amountDen: 1,
          unit: "",
          name: "eggs",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1.5,
          amountDen: 1,
          unit: "cups",
          name: "flour",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 2,
          amountDen: 1,
          unit: "cups",
          name: "Bread crumbs",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 2,
          amountDen: 1,
          unit: "tsp",
          name: "dried basil",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "tsp",
          name: "dried thyme",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 2,
          amountDen: 1,
          unit: "pounds",
          name: "veal scallopine",
          consistency: "",
          meta: "Thinly sliced",
        },
        {
          amountNum: 0,
          amountDen: 0,
          unit: "",
          name: "salt and pepper",
          consistency: "",
          meta: "to taste",
        },
      ],
      preparation: [
        {
          step: 1,
          description:
            "Preheat oven to 175 degrees F. In a shallow dish, beat eggs and season with salt and pepper. Pour flour into another shallow dish. Mix together the bread crumbs, basil and thyme in a third shallow dish. Have ready one large plate.",
          stepImage:
            "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2003/11/3/0/ei1a03_veal_milanese.jpg.rend.hgtvcom.826.620.suffix/1386773166905.jpeg",
        },
        {
          step: 2,
          description:
            "Season the veal with salt and pepper. Working with 1 piece of veal at a time, dip it first in the flour, shaking off excess. Next, place the floured veal into the beaten eggs, coating completely. Place the veal into the bread crumb mixture and gently press crumbs into the veal. Set aside on large plate and continue with remaining veal slices.",
          stepImage:
            "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2003/11/3/0/ei1a03_veal_milanese.jpg.rend.hgtvcom.826.620.suffix/1386773166905.jpeg",
        },
        {
          step: 3,
          description:
            "In a large skillet with high sides, heat the oil to 375 degrees F. Have ready a baking sheet fitted with a rack. Carefully place 2 pieces of breaded veal in the hot oil and fry until golden brown on both sides, about 6 to 8 minutes total. Place cooked veal on rack, season with salt and place in oven to keep warm. Continue with remaining veal.",
          stepImage:
            "https://food.fnr.sndimg.com/content/dam/images/food/fullset/2003/11/3/0/ei1a03_veal_milanese.jpg.rend.hgtvcom.826.620.suffix/1386773166905.jpeg",
        },
      ],
      filters: {
        healthy: false,
        seasonal: false,
        min30: true,
        glutenFree: false,
        vegetarian: false,
        breakfast: false,
        lunch: false,
        dinner: true,
        dessert: false,
        snack: false,
        indian: false,
        thai: false,
        japanese: false,
        french: false,
        italian: true,
        mexican: false,
        american: false,
        canadian: false,
        korean: false,
        polish: false,
      },
      comments: [
        {
          commentAuthor: "Dan Dalgatov",
          commentDetails: "This dish is perfect for a hungry developer",
          commentTime: "1592459790537",
        },
      ],
    },

    {
      title: "Focaccia bread",
      coverImage:
        "https://www.gimmesomeoven.com/wp-content/uploads/2017/03/Rosemary-Focaccia-Bread-Recipe-1-2-1100x1650.jpg",
      servesPeople: 6,
      cookTime: 25,
      cookTimeUnit: "Minutes",
      ingredients: [
        {
          amountNum: 2.75,
          amountDen: 1,
          unit: "",
          name: "flour",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "tsp",
          name: "salt",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "tbs",
          name: "sugar",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 2,
          unit: "tsp",
          name: "dried basil",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "tsp",
          name: "dried thyme",
          consistency: "",
          meta: "",
        },

        {
          amountNum: 1,
          amountDen: 1,
          unit: "tbs",
          name: "active dry yeast",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "tsp",
          name: "garlic powder",
          consistency: "",
          meta: "to taste",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "tsp",
          name: "pepper",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "tbs",
          name: "salt and pepper",
          consistency: "",
          meta: "to taste",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "tsp",
          name: "dried oregano",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 0,
          amountDen: 0,
          unit: "",
          name: "salt and pepper",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "tbs",
          name: "vegitable oil",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "cup",
          name: "water",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 2,
          amountDen: 1,
          unit: "tbs",
          name: "olive oil",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "cup",
          name: "mozzarella",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 1,
          unit: "tbs",
          name: "parmersan",
          consistency: "",
          meta: "",
        },
      ],
      preparation: [
        {
          step: 1,
          description:
            "In a large bowl, stir together the flour, salt, sugar, yeast, garlic powder, oregano, thyme, basil and black pepper. Mix in the vegetable oil and water.",
          stepImage:
            "https://www.gimmesomeoven.com/wp-content/uploads/2017/03/Rosemary-Focaccia-Bread-Recipe-2-1100x1650.jpg",
        },
        {
          step: 2,
          description:
            "When the dough has pulled together, turn it out onto a lightly floured surface, and knead until smooth and elastic. Lightly oil a large bowl, place the dough in the bowl, and turn to coat with oil. Cover with a damp cloth, and let rise in a warm place for 20 minutes.",
          stepImage:
            "https://www.gimmesomeoven.com/wp-content/uploads/2017/03/Rosemary-Focaccia-Bread-Recipe-6-1100x1650.jpg",
        },
        {
          step: 3,
          description:
            "Preheat oven to 450 degrees F (230 degrees C). Punch dough down; place on greased baking sheet. Pat into a 1/2 inch thick rectangle. Brush top with olive oil. Sprinkle with Parmesan cheese and mozzarella cheese. Bake in preheated oven for 15 minutes, or until golden brown. Serve warm.",
          stepImage:
            "https://www.gimmesomeoven.com/wp-content/uploads/2017/03/Rosemary-Focaccia-Bread-Recipe-4-1100x1650.jpg",
        },
      ],
      filters: {
        healthy: false,
        seasonal: false,
        min30: true,
        glutenFree: false,
        vegetarian: true,
        breakfast: true,
        lunch: true,
        dinner: true,
        dessert: false,
        snack: false,
        indian: false,
        thai: false,
        japanese: false,
        french: false,
        italian: true,
        mexican: false,
        american: false,
        canadian: false,
        korean: false,
        polish: false,
      },
      comments: [
        {
          commentAuthor: "Dan Dalgatov",
          commentDetails: "This dish is perfect for a hungry developer",
          commentTime: "1592459790537",
        },
      ],
    },
    {
      title: "Oven Baked Korean BBQ Beef Ribs",
      coverImage: "https://i.imgur.com/3znSL1M.png",
      servesPeople: 2,
      cookTime: 1,
      cookTimeUnit: "Hour",
      ingredients: [
        {
          amount: 4,
          unit: "lbs",
          name: "beef spare ribs",
          consistency: "",
          meta: "",
        },
        {
          amount: 1,
          unit: "cup",
          name: "brown sugar",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 4,
          unit: "cup",
          name: "rice wine",
          consistency: "(mirin)",
          meta: "",
        },
        {
          amount: 1,
          unit: "",
          name: "onion",
          consistency: "",
          meta: "",
        },
        {
          amount: 2,
          unit: "tbsp",
          name: "minced garlic",
          consistency: "",
          meta: "",
        },
        {
          amount: 2,
          unit: "tbsp",
          name: "ginger",
          consistency: "minced",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 4,
          unit: "tsp",
          name: "black pepper",
          consistency: "",
          meta: "",
        },
      ],
      preparation: [
        {
          step: 1,
          description:
            "Pour the marinade over the meat and make sure it's reaching all parts of the meat. Cover the meat and transfer it to the fridge. Marinate the meat for at least 4 hrs (but ideally for 24 hrs for optimal results).",
          stepImage:
            "https://mykoreankitchen.com/wp-content/uploads/2016/10/6.-Marinating-Spare-Ribs-for-Oven-Baked-Korean-BBQ-Beef-Ribs.jpg",
        },
        {
          step: 2,
          description:
            "Preheat the oven on 100 C/ 212 F (on fan forced setting) for 20 mins. Lay down some waxed baking paper (or aluminium foil) on a baking sheet (or roasting pan). Then place the marinated rack of ribs. Splash some marinade around the ribs but discard most of sauce. Cook it for 8 hrs.",
          stepImage:
            "https://mykoreankitchen.com/wp-content/uploads/2016/10/2.-Oven-Baked-Korean-BBQ-Beef-Ribs.jpg",
        },
        {
          step: 3,
          description: "Take the meat out and carve. Serve.",
          stepImage:
            "https://mykoreankitchen.com/wp-content/uploads/2016/10/3.-Oven-Baked-Korean-BBQ-Beef-Ribs.jpg",
        },
      ],
      filters: {
        healthy: false,
        seasonal: false,
        min30: false,
        glutenFree: false,
        vegetarian: false,
        breakfast: false,
        lunch: true,
        dinner: true,
        dessert: false,
        snack: false,
        indian: false,
        thai: false,
        japanese: false,
        french: false,
        italian: false,
        mexican: false,
        american: true,
        canadian: false,
        korean: true,
        polish: false,
      },
      comments: [
        {
          commentAuthor: "Chris Knobling",
          commentDetails: "I want to bathe in a tub of this.",
          commentTime: "1592459790537",
        },
      ],
    },
    {
      title: "Beef Bulgogi Korean Tacos",
      coverImage: "https://i.imgur.com/3znSL1M.png",
      servesPeople: 8,
      cookTime: 1,
      cookTimeUnit: "Hour",
      ingredients: [
        {
          amount: 3,
          unit: "",
          name: "medium green onions",
          consistency: "chopped",
          meta: "",
        },
        {
          amount: 3,
          unit: "tablespoons",
          name: "sugar",
          consistency: "",
          meta: "",
        },
        {
          amount: 2,
          unit: "tablespoons",
          name: "vegetable oil",
          consistency: "",
          meta: "",
        },
        {
          amount: 1,
          unit: "lb",
          name: "beef top sirloin steak",
          consistency: "thinly sliced against the grain",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 4,
          unit: "cup",
          name: "soy sauce",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 2,
          unit: "cup",
          name: "salsa",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 2,
          unit: "teaspoon",
          name: "fresh lime juice",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 2,
          unit: "table spoon",
          name: "soy sauce",
          consistency: "",
          meta: "",
        },
        {
          amount: 1,
          unit: "cup",
          name: "fresh cilantro sprigs",
          consistency: "",
          meta: "",
        },
        {
          amountNum: 1,
          amountDen: 2,
          unit: "cup",
          name: "thinly sliced red onion",
          consistency: "",
          meta: "",
        },
        {
          amount: 2,
          unit: "cups",
          name: "romaine lettuce",
          consistency: "thinnly cut",
          meta: "",
        },
      ],
      preparation: [
        {
          step: 1,
          description:
            "In 1-gallon resealable food storage plastic bag, mix beef and marinade ingredients. Seal bag. Refrigerate 30 mins.",
          stepImage: "https://i.imgur.com/mVgiec0.png",
        },
        {
          step: 2,
          description:
            "Meanwhile, in blender, place spicy salsa ingredients. Cover; blend on medium speed until smooth. Pour into small bowl. Set aside, in large bowl, mix all slaw ingredients except lettuce until well mixed. Set aside.",
          stepImage: "https://i.imgur.com/J6UU6Yw.png",
        },
        {
          step: 3,
          description:
            "Drain beef; discard marinade. Heat 12-inch nonstick skillet over medium-high heat. Cook beef in skillet 2 to 3 minutes, stirring frequently, until brown. Toss lettuce in slaw mixture. Spoon beef on warm tortillas. Drizzle with spicy salsa, and top with slaw. Sprinkle tops with sesame seed.",
          stepImage: "https://i.imgur.com/7QIhXPs.png",
        },
      ],
      filters: {
        healthy: false,
        seasonal: false,
        min30: false,
        glutenFree: false,
        vegetarian: false,
        breakfast: false,
        lunch: true,
        dinner: true,
        dessert: false,
        snack: false,
        indian: false,
        thai: false,
        japanese: false,
        french: false,
        italian: false,
        mexican: false,
        american: true,
        canadian: false,
        korean: true,
        polish: false,
      },
      comments: [
        {
          commentAuthor: "French Montana",
          commentDetails: "I'll write a song about these babies.",
          commentTime: "1592459790537",
        },
      ],
    },
  ];

  await Recipe.insertMany(recipes);
  console.log("Created recipes!");
};
const run = async () => {
  await main();
  db.close();
};
run();
